=== rainysteven1/Crack/resources/config/configuration_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Configruation",
  "type": "object",
  "properties": {
    "data path": {
      "type": "object",
      "properties": {
        "data_path": {
          "type": "string"
        },
        "category_list": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "img_dir_list": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": ["data_path", "category_list", "img_dir_list"]
    },
    "data attributes": {
      "type": "object",
      "properties": {
        "batch_height": {
          "type": "integer"
        },
        "batch_width": {
          "type": "integer"
        }
      },
      "required": ["batch_height", "batch_width"]
    },
    "train settings": {
      "type": "object",
      "properties": {
        "batch_size": {
          "type": "integer"
        },
        "N_epochs": {
          "type": "integer"
        },
        "train_split": {
          "type": "integer"
        },

        "criterion": {
          "type": "string",
          "enum": [
            "BCELoss",
            "DiceLoss",
            "BCEDiceLoss",
            "FocalLoss",
            "IoULoss",
            "HybridLoss1"
          ]
        },
        "optimizer": {
          "anyOf": [
            {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string",
                  "const": "Adam"
                },
                "lr": {
                  "type": "number"
                },
                "eps": {
                  "type": "number"
                },
                "amsgrad": {
                  "type": "boolean"
                }
              },
              "required": ["name"]
            },
            {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string",
                  "const": "SGD"
                },
                "lr": {
                  "type": "number"
                },
                "momentum": {
                  "type": "number"
                },
                "weight_decay": {
                  "type": "number"
                },
                "nesterov": {
                  "type": "boolean"
                }
              },
              "required": ["name"]
            },
            {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string",
                  "const": "AdamW"
                },
                "lr": {
                  "type": "number"
                },
                "weight_decay": {
                  "type": "number"
                }
              },
              "required": ["name"]
            }
          ]
        },
        "scheduler": {
          "anyOf": [
            {
              "type": "object",
              "properties": {
                "name": { "type": "string", "const": "LambdaLR" },
                "lrf": {
                  "type": "number"
                },
                "lr_lambda": {
                  "type": "string",
                  "enum": ["lr_schedule1", "lr_schedule2"]
                }
              },
              "required": ["name", "lr_lambda"]
            },
            {
              "type": "object",
              "properties": {
                "name": { "type": "string", "const": "ReduceLROnPlateau" },
                "mode": { "type": "string", "enum": ["max", "min"] },
                "patience": { "type": "integer" }
              },
              "required": ["name"]
            },
            {
              "type": "object",
              "properties": {
                "name": { "type": "string", "const": "CosineAnnealingLR" },
                "T_max": { "type": "integer" },
                "eta_min": { "type": "number" }
              },
              "required": ["name"]
            }
          ]
        },
        "early_stopping_patience": { "type": "integer" }
      },
      "required": [
        "batch_size",
        "N_epochs",
        "train_split",
        "criterion",
        "optimizer",
        "early_stopping_patience"
      ]
    },
    "test settings": {
      "type": "object",
      "properties": {
        "best_last": {
          "type": "string"
        },
        "batch_size": {
          "type": "integer"
        },
        "metrics_mode": {
          "type": "string"
        }
      },
      "required": ["best_last", "batch_size", "metrics_mode"]
    },
    "result settings": {
      "type": "object",
      "properties": {
        "folder_list": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": ["folder_list"]
    }
  },
  "required": [
    "data path",
    "data attributes",
    "train settings",
    "test settings",
    "result settings"
  ]
}

=== rainysteven1/Crack/resources/config/unet_ppp.json
{
  "data path": {
    "data_path": "/Users/rainy/code/deep-learning/Data/crack500",
    "category_list": ["train", "test", "validation"],
    "img_dir_list": ["image", "groundtruth", "mask"]
  },
  "data attributes": {
    "batch_height": 256,
    "batch_width": 256
  },
  "train settings": {
    "batch_size": 4,
    "N_epochs": 100,
    "train_split": 1500,
    "criterion": "HybridLoss1",
    "optimizer": {
      "name": "AdamW",
      "lr": 1e-3,
      "weight_decay": 1e-4
    },
    "scheduler": {
      "name": "LambdaLR",
      "lrf": 5e-4,
      "lr_lambda": "lr_schedule2"
    },
    "early_stopping_patience": -1
  },
  "test settings": {
    "best_last": "best",
    "batch_size": 8,
    "metrics_mode": "gpu"
  },
  "result settings": {
    "folder_list": ["code", "config", "figure", "log", "model"]
  }
}

=== rainysteven1/Crack/resources/config/resunet_pp.json
{
  "data path": {
    "data_path": "/Users/rainy/code/deep-learning/Data/crack500",
    "category_list": ["train", "test", "validation"],
    "img_dir_list": ["image", "groundtruth", "mask"]
  },
  "data attributes": {
    "batch_height": 256,
    "batch_width": 256
  },
  "train settings": {
    "batch_size": 4,
    "N_epochs": 100,
    "train_split": 1500,
    "criterion": "DiceLoss",
    "optimizer": {
      "name": "Adam",
      "lr": 0.0035,
      "eps": 1e-7,
      "amsgrad": true
    },
    "scheduler": {
      "name": "LambdaLR",
      "lr_lambda": "lr_schedule1"
    },
    "early_stopping_patience": -1
  },
  "test settings": {
    "best_last": "best",
    "batch_size": 20,
    "metrics_mode": "gpu"
  },
  "result settings": {
    "folder_list": ["code", "config", "figure", "log", "model"]
  }
}

=== rainysteven1/Crack/resources/config/unet_pp.json
{
  "data path": {
    "data_path": "/Users/rainy/code/deep-learning/Data/crack500",
    "category_list": ["train", "test", "validation"],
    "img_dir_list": ["image", "groundtruth", "mask"]
  },
  "data attributes": {
    "batch_height": 256,
    "batch_width": 256
  },
  "train settings": {
    "batch_size": 4,
    "N_epochs": 100,
    "train_split": 1500,
    "criterion": "BCELoss",
    "optimizer": {
      "name": "SGD",
      "lr": 1e-3,
      "momentum": 0.9,
      "weight_decay": 1e-4,
      "nesterov": false
    },
    "scheduler": {
      "name": "CosineAnnealingLR",
      "T_max": 100,
      "eta_min": 1e-5
    },
    "early_stopping_patience": -1
  },
  "test settings": {
    "best_last": "best",
    "batch_size": 20,
    "metrics_mode": "gpu"
  },
  "result settings": {
    "folder_list": ["code", "config", "figure", "log", "model"]
  }
}

=== rainysteven1/Crack/resources/config/setr.json
{
  "data path": {
    "data_path": "/Users/rainy/code/deep-learning/Segmentations/U-Net/Crack/resources/data/crack500",
    "category_list": [
      "train",
      "test",
      "validation"
    ],
    "img_dir_list": [
      "image",
      "groundtruth",
      "mask"
    ]
  },
  "data attributes": {
    "batch_height": 256,
    "batch_width": 256
  },
  "train settings": {
    "batch_size": 4,
    "N_epochs": 100,
    "train_split": 1500,
    "criterion": "BCEDiceLoss",
    "optimizer": {
      "name": "Adam",
      "lr": 0.00001,
      "weight_decay": 0.00001
    },
    "scheduler": {
      "name": "ReduceLROnPlateau",
      "mode": "min",
      "patience": 5
    },
    "early_stopping_patience": 50,
    "config": "ViT-B_16"
  },
  "test settings": {
    "best_last": "best",
    "batch_size": 8,
    "metrics_mode": "gpu",
    "config": "testing"
  },
  "result settings": {
    "folder_list": [
      "code",
      "config",
      "figure",
      "log",
      "model"
    ]
  }
}
